import React, { useState, useEffect, useRef } from "react";
import Loader from "../components/Loader";
import FormField from "../components/FormField";
import Card from "../components/Card";

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return (
      <>
        {data.map((post) => (
          <Card key={post._id} {...post} />
        ))}
      </>
    );
  }

  return (
    <h2 className="mt-5 font-black text-[#6469ff] text-xl uppercase">
      {title || "No posts available"}
    </h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState([]);
  const [searchText, setSearchText] = useState("");
  const [searchedResults, setSearchedResults] = useState([]);
  const [error, setError] = useState(null);
  const debounceRef = useRef();

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
      setError(null);
      try {
        const response = await fetch("http://localhost:3000/api/v1/post", {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        });

        if (!response.ok) {
          throw new Error(`Failed to fetch posts: ${response.status}`);
        }

        const result = await response.json();
        setAllPosts(result.data || []);
      } catch (error) {
        console.error("Fetch error:", error);
        setError(error.message);
      } finally {
        setLoading(false);
      }
    };

    fetchPosts();
  }, []);

  const handleSearchChange = (e) => {
    const value = e.target.value;
    setSearchText(value);

    clearTimeout(debounceRef.current);

    if (!value.trim()) {
      setSearchedResults([]);
      return;
    }

    debounceRef.current = setTimeout(() => {
      const searchResults = allPosts.filter(
        (item) =>
          item.name?.toLowerCase().includes(value.toLowerCase()) ||
          item.prompt?.toLowerCase().includes(value.toLowerCase())
      );
      setSearchedResults(searchResults);
    }, 500);
  };

  useEffect(() => {
    return () => {
      clearTimeout(debounceRef.current);
    };
  }, []);

  return (
    <section className="max-w-7xl mx-auto p-4">
      <div>
        <h1 className="font-bold text-4xl text-[#222328]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[590px]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>

      <div className="mt-16">
        <FormField
          labelName="Search Posts"
          type="text"
          name="search"
          placeholder="Search by name or prompt"
          value={searchText}
          handleChange={handleSearchChange} // ✅ prop passed correctly
        />
      </div>

      <div className="mt-10">
        {error && (
          <div className="text-red-500 mb-4 p-2 bg-red-50 rounded">
            Error: {error}
          </div>
        )}

        {loading ? (
          <div className="flex justify-center items-center h-64">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                {searchedResults.length > 0
                  ? `Showing results for "${searchText}"`
                  : `No results found for "${searchText}"`}
              </h2>
            )}

            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              <RenderCards
                data={searchText ? searchedResults : allPosts}
                title={
                  searchText
                    ? "No matching posts found"
                    : allPosts.length === 0
                    ? "No posts available"
                    : ""
                }
              />
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;